/**
 * Major Pakistani cities for marketplace location filters (hero + browse).
 */
export const PAKISTAN_MAJOR_CITIES: readonly string[] = [
  "Abbottabad",
  "Attock",
  "Bahawalnagar",
  "Bahawalpur",
  "Bannu",
  "Bhakkar",
  "Burewala",
  "Chaman",
  "Charsadda",
  "Chiniot",
  "Dera Ghazi Khan",
  "Dera Ismail Khan",
  "Faisalabad",
  "Gilgit",
  "Gojra",
  "Gujranwala",
  "Gujrat",
  "Gwadar",
  "Hafizabad",
  "Haripur",
  "Hyderabad",
  "Islamabad",
  "Jacobabad",
  "Jhang",
  "Jhelum",
  "Karachi",
  "Kasur",
  "Khanewal",
  "Khuzdar",
  "Kohat",
  "Kot Addu",
  "Lahore",
  "Larkana",
  "Lodhran",
  "Mansehra",
  "Mardan",
  "Mirpur Khas",
  "Multan",
  "Muzaffarabad",
  "Muzaffargarh",
  "Narowal",
  "Nawabshah",
  "Okara",
  "Pakpattan",
  "Peshawar",
  "Quetta",
  "Rahim Yar Khan",
  "Rawalpindi",
  "Sadiqabad",
  "Sahiwal",
  "Sargodha",
  "Sheikhupura",
  "Shikarpur",
  "Sialkot",
  "Skardu",
  "Sukkur",
  "Swabi",
  "Swat",
  "Taxila",
  "Timergara",
  "Toba Tek Singh",
  "Vehari",
  "Wah Cantonment",
]
